### ISSUE TITLE
监控 bug 和参数bug

### ISSUE THREAD

**Issue by liangbaika** [Chris2018998/BeeCP-Starter#8]
1 配置了多个数据原  监控页只出现了一个
![image](https://user-images.githubusercontent.com/33059022/103731969-61ce8780-5021-11eb-90cd-85154edecbea.png)
![image](https://user-images.githubusercontent.com/33059022/103731989-6e52e000-5021-11eb-8968-382bb946bac4.png)

2 无法查看监控的sql  报错了
![image](https://user-images.githubusercontent.com/33059022/103731939-511e1180-5021-11eb-9d5c-8827bb7aae2c.png)
![image](https://user-images.githubusercontent.com/33059022/103731961-5bd8a680-5021-11eb-98dd-b7503e19f274.png)

3 配置的参数 没有进行检查 导致我这边找了很久的原因 因为配置写错了
 一开始 这样写的 写错了 ds1 ds2的位置 

![image](https://user-images.githubusercontent.com/33059022/103731933-4bc0c700-5021-11eb-92b0-dc42cea9a240.png)

 以上这些问题能不能尽快修复啊 后边马上准备用了

**Comment by liangbaika** [comment]
@Chris2018998

**Comment by Chris2018998** [comment]
好的，我尽快修复，Github的图片在我这边显示不出来，有没有其他地方分享一下？

**Comment by liangbaika** [comment]
加个联系方式？交流下  QQ wechat都行------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;欧德&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月7日(星期四) 晚上7:53
收件人:&nbsp;&quot;Chris2018998/BeeCP-Starter&quot;<BeeCP-Starter@noreply.github.com&gt;;
抄送:&nbsp;&quot;凉白开&quot;<1144388620@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Chris2018998/BeeCP-Starter] 监控 bug 和参数bug (#8)

**Comment by Chris2018998** [comment]
加强一下了代码，开发了一个新版本，可以试试：
https://github.com/Chris2018998/BeeCP-Starter/blob/master/doc/beecp-spring-boot-starter-1.4.2.jar

如果下载不了，请到地址：https://gitee.com/mirrors/BeeCP-Starter 下载

此账户是即个人微信。。。。

**Comment by liangbaika** [comment]
发到你邮箱去了 
Chris2018998<chris2018998@tom.com>

**Comment by Chris2018998** [comment]
好的，看到了。我晚上按图片方式验证一下。

**Comment by Chris2018998** [comment]
yml格式确实有这个问题

```
<dependency>
   <groupId>com.github.chris2018998</groupId>
   <artifactId>beecp-spring-boot-starter</artifactId>
   <version>1.4.2</version>
</dependency>
```





```
spring:
  application:
    name: dsDemo
  datasource:
    monitor-login: true
    monitor-password: admin
    monitor-user: admin
    sql-exec-alert-action: cn.beecp.boot.monitor.sqltrace.SqlTraceAlert
    sql-exec-alert-time: 1
    sql-show: true
    sql-trace: true
    sql-trace-max-size: 8000
    sql-trace-timeout: 60000
    sql-trace-timeout-scan-period: 18000
    nameList: ds1,ds2
    ds1:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/test
      password: ''
      primary: true
      username: root
    ds2:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/test
      password: ''
      username: root

```
